# Project info
site_name: AutoRadiomics
site_description: The easiest tool for experimenting with Radiomics features
site_author: Piotr Woznicki

docs_dir: docs

# Repository
repo_url: https://github.com/pwoznicki/AutoRadiomics
repo_name: pwoznicki/AutoRadiomics

# Configuration
theme:
  name: readthedocs

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight

# Plugins
plugins:
  - search
  - mkdocstrings

# Page tree
nav:
  - Home:
      - AutoRadiomics: index.md
  - Reference:
      - Data: autorad/data.md
      - Feature Extraction: autorad/feature_extractor.md
      - Feature Selection: autorad/feature_selector.md
      - Models: autorad/models.md
      - Trainer: autorad/trainer.md
      - Visualization: autorad/plotly_utils.md
