[build-system]
requires = [
   "setuptools>=42",
   "wheel",
   "Cython>=0.15.1",
   "numpy>=1.10"
]
build-backend = "setuptools.build_meta"

# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
