name: Build web application

on:
  push:
    branches:
    - executable-app
  pull_request:
    branches:
    - main
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu"]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install -U pip
    - name: Install Node
      uses: actions/setup-node@v3
      with:
         node-version: "16"
    - name: make build app
      run: |
        make build-pyoxidizer
        cd js/app/
        yarn install
        yarn build
    - uses: actions/upload-artifact@v3
      with:
        name: AutoRadiomicsApp-${{ runner.os }}
        path: |
          js/app/dist/*.zip
          js/app/dist/*.exe
          js/app/dist/*.AppImage
          !js/app/dist/*unpacked/
