imageType:
  Original: {}

featureClass:
  firstorder: []
  glcm: []
  glrlm: []
  glszm: []
  gldm: []
  ngtdm: []

setting:
  normalize: true
  normalizeScale: 500
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [2, 2, 2]
  binWidth: 25
  voxelArrayShift: 1000  # Minimum value in HU is -1000, shift +1000 to prevent negative values from being squared.
  label: 1
